### PR TITLE
support displaying bd cad objects with color tagged

### PR DESCRIPTION
**Pull request by chaserhkj**
This PR adds support for YACV to display different colors in objects as set forth in build123d objects in "color" attributes.

This is particularly helpful when working with larger assemblies where there are a number of components and different colors are used to distinguish them

### CODE REVIEW

**Comment by Yeicor** [comment]
Nice idea and nice work! I still have to test it locally when I have some time but I have an initial question:

Should we also support colors for edges and vertices? I know it is a less likely use case, but if build123d supports it (does it?), we should too. Also, to avoid painting everything the same way, we could set it up so that edges are only colored when no faces are present, and vertices only when neither edges nor faces exist. This would give the user more control over how to paint each part of the model or assembly.

Are you willing to implement this change?

**Comment by chaserhkj** [comment]
I just had a quick look into it. build123d has `color` attribute defined on the `Shape` base class, so technically any shape can have color. But I am no so sure about whether a b123d solid object's component faces and edges can have different colors (rather than the main color defined on the solid object). The problem is wrapped `TopoDS_Shape` objects do not have color attributes, so I am not sure if the color of component edges and vertices are preserved after they are added to form the solid, I need to look into this deeper, but I might not have immediate time for it.

I can get back in one week or two with a follow-up and maybe the implementation if it is doable.

**Comment by Yeicor** [comment]
During my testing, I added basic coloring support for edges and vertices, but only when they are the primary feature passed to `show()`. Here's how it works:

- If the object has faces, only the faces are colored.
- If there are no faces but edges exist, the edges are colored.
- If neither faces nor edges exist, the vertices are colored.

This setup allows for highlighting specific parts of an object by applying different colors, although it requires adding a separate model for the highlights. While this solution works for now, we can revisit it if build123d supports coloring individual parts of an object.

Currently, both the example and the logo make use of custom colors for faces and edges.

Screenshot_20241011_200405

I will release v0.9.0 with these changes.

**Comment by chaserhkj** [comment]
Thanks for the follow up! Was quite occupied by other stuff in the past few weeks...

I just double checked to make sure but it did seem that build123d does not support coloring different colors on the same object at the moment, so I guess this is the best we can do right now.

**Pull request merged**
